#pragma config(Sensor, S1,     Sonar,          sensorSONAR)
#pragma config(Sensor, S2,     Sync,           sensorTouch)
#pragma config(Sensor, S4,     LDR,            sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/////////////////////////////////////////////////////////
//////////////////////ABSTRACT///////////////////////////
/////////////////////////////////////////////////////////
//This sample is designed to be used with a NXT brick and only two servos, yet it has the ability to scan
//It uses a seperate lego motor for moving the ultrasonic sensor and an pushbutton + reflection sensor as a encoder for syncing the readout
//The scanner readout is displayed on the NXT screen.
//
//The program starts 2 threads, one for scanning and one for using the scan data for navigation and movement.
//Three simple motor control functions are used for committing maneuvers.
//
//
//Created by Christopher Randmaa for demonstrating complex C-written code on the NXT V2 Brick for Educational Purposes in the Tallinn Polytechnic School(TPT, tpt.edu.ee)
//GPL, 2013.
/////////////////////////////////////////////////////////
/////////////////////////////////////////////////////////

#include "Configuration.c"//important global variables/settings
#include "Error.c"// Error handling functions
#include "Motors.c"// Motor control functions
#include "Encoder.c"// Encoder task and functions
#include "Scanner.c"// Scanner task and functions
#include "Navigate.c"// Navigation task and functions

//////////////////////////
////////MAIN LOOP/////////
//////////////////////////
task main()
{
  GetPulseCount();
  StartTask(TScanCycle);
  StartTask(TNav);
  StartTask(TEnc);
//  StartTask(TMot);
  const int maxsel = 5;
  string ViewNames[maxsel + 1];// stores the ...viewnames
  int tempsel = 0; //keep initial view value in a different variable, before checking its bounds(multithreading issues)
  ViewNames[0] = "Raw scan data";
  ViewNames[1] = "Averaged Sectors";
  ViewNames[2] = "A.+Blurred sectors";
  ViewNames[3] = "A.+B.+Weighted";
  ViewNames[4] = "Variables";
  ViewNames[5] = "Speed Graph";

  while(true)
  {
    if(bError)
    {
      StopMot = true;
      DrawView = 99;//stop showing views
      HandleError();
      DrawView = tempsel;
    }

    wait1Msec(300);//chill around

    if(nNxtButtonPressed == 1)
      tempsel++;

    if(nNxtButtonPressed == 2)
      tempsel--;

    if(nNxtButtonPressed == 3)
    {
      DrawView = 99;//stop showing views
      StopMot = !StopMot;
      eraseDisplay();
      nxtDisplayCenteredTextLine(0, "Motors");//show selected view name
      if(StopMot)
        nxtDisplayCenteredBigTextLine(2, "OFF");//show selected view number
      else
        nxtDisplayCenteredBigTextLine(2, "ON");//show selected view number
      wait1Msec(500);//wait a sec
      DrawView = tempsel;// set View
    }
    else if(nNxtButtonPressed == 2 || nNxtButtonPressed == 1)
    {
      if(tempsel > maxsel)
        tempsel = 0;
      if(tempsel < 0)
        tempsel = maxsel;

      DrawView = 99;//stop showing views
      eraseDisplay();
      nxtDisplayCenteredTextLine(0, ViewNames[tempsel]);//show selected view name
      nxtDisplayCenteredBigTextLine(2, "%d", tempsel);//show selected view number
      wait1Msec(500);//wait a sec
      DrawView = tempsel;// set View
    }
  }
  return;
}
